// Friend suggestions
export const FETCH_FRIEND_SUGGESTIONS_REQUEST =
  "FETCH_FRIEND_SUGGESTIONS_REQUEST";
export const FETCH_FRIEND_SUGGESTIONS_SUCCESS =
  "FETCH_FRIEND_SUGGESTIONS_SUCCESS";
export const FETCH_FRIEND_SUGGESTIONS_FAILURE =
  "FETCH_FRIEND_SUGGESTIONS_FAILURE";

// Send friend request
export const SEND_FRIEND_REQUEST_REQUEST = "SEND_FRIEND_REQUEST_REQUEST";
export const SEND_FRIEND_REQUEST_SUCCESS = "SEND_FRIEND_REQUEST_SUCCESS";
export const SEND_FRIEND_REQUEST_FAILURE = "SEND_FRIEND_REQUEST_FAILURE";

// Get friend requests
export const FETCH_FRIEND_REQUESTS_REQUEST = "FETCH_FRIEND_REQUESTS_REQUEST";
export const FETCH_FRIEND_REQUESTS_SUCCESS = "FETCH_FRIEND_REQUESTS_SUCCESS";
export const FETCH_FRIEND_REQUESTS_FAILURE = "FETCH_FRIEND_REQUESTS_FAILURE";

// Accept/reject friend request
export const RESPOND_TO_FRIEND_REQUEST_REQUEST =
  "RESPOND_TO_FRIEND_REQUEST_REQUEST";
export const RESPOND_TO_FRIEND_REQUEST_SUCCESS =
  "RESPOND_TO_FRIEND_REQUEST_SUCCESS";
export const RESPOND_TO_FRIEND_REQUEST_FAILURE =
  "RESPOND_TO_FRIEND_REQUEST_FAILURE";

// Add this new action type
export const ADD_NEW_FRIEND_REQUEST = "ADD_NEW_FRIEND_REQUEST";

// Remove friend request
export const REMOVE_FRIEND_REQUEST = "REMOVE_FRIEND_REQUEST";

export const FETCH_FRIENDS_REQUEST = "FETCH_FRIENDS_REQUEST";
export const FETCH_FRIENDS_SUCCESS = "FETCH_FRIENDS_SUCCESS";
export const FETCH_FRIENDS_FAILURE = "FETCH_FRIENDS_FAILURE";

export const SET_ACCESS_LEVEL_REQUEST = "SET_ACCESS_LEVEL_REQUEST";
export const SET_ACCESS_LEVEL_SUCCESS = "SET_ACCESS_LEVEL_SUCCESS";
export const SET_ACCESS_LEVEL_FAILURE = "SET_ACCESS_LEVEL_FAILURE";

export const FETCH_I_SHARED_WITH_REQUEST = "FETCH_I_SHARED_WITH_REQUEST";
export const FETCH_I_SHARED_WITH_SUCCESS = "FETCH_I_SHARED_WITH_SUCCESS";
export const FETCH_I_SHARED_WITH_FAILURE = "FETCH_I_SHARED_WITH_FAILURE";

export const FETCH_SHARED_WITH_ME_REQUEST = "FETCH_SHARED_WITH_ME_REQUEST";
export const FETCH_SHARED_WITH_ME_SUCCESS = "FETCH_SHARED_WITH_ME_SUCCESS";
export const FETCH_SHARED_WITH_ME_FAILURE = "FETCH_SHARED_WITH_ME_FAILURE";
