export const FETCH_CATEGORIES_REQUEST = "FETCH_CATEGORIES_REQUEST";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAILURE = "FETCH_CATEGORIES_FAILURE";
export const FETCH_UNCATEGORIZED_EXPENSES_REQUEST =
  "FETCH_UNCATEGORIZED_EXPENSES_REQUEST";
export const FETCH_UNCATEGORIZED_EXPENSES_SUCCESS =
  "FETCH_UNCATEGORIZED_EXPENSES_SUCCESS";
export const FETCH_UNCATEGORIZED_EXPENSES_FAILURE =
  "FETCH_UNCATEGORIZED_EXPENSES_FAILURE";
export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAILURE = "CREATE_CATEGORY_FAILURE";
