export const FETCH_CATEGORIES_REQUEST = "FETCH_CATEGORIES_REQUEST";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAILURE = "FETCH_CATEGORIES_FAILURE";
export const FETCH_UNCATEGORIZED_EXPENSES_REQUEST =
  "FETCH_UNCATEGORIZED_EXPENSES_REQUEST";
export const FETCH_UNCATEGORIZED_EXPENSES_SUCCESS =
  "FETCH_UNCATEGORIZED_EXPENSES_SUCCESS";
export const FETCH_UNCATEGORIZED_EXPENSES_FAILURE =
  "FETCH_UNCATEGORIZED_EXPENSES_FAILURE";
export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAILURE = "CREATE_CATEGORY_FAILURE";

// Category action types
export const FETCH_CATEGORY_REQUEST = "FETCH_CATEGORY_REQUEST";
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const FETCH_CATEGORY_FAILURE = "FETCH_CATEGORY_FAILURE";

export const UPDATE_CATEGORY_REQUEST = "UPDATE_CATEGORY_REQUEST";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAILURE = "UPDATE_CATEGORY_FAILURE";
export const UPDATE_CATEGORY_IN_LIST = "UPDATE_CATEGORY_IN_LIST";

export const FETCH_CATEGORY_EXPENSES_REQUEST =
  "FETCH_CATEGORY_EXPENSES_REQUEST";
export const FETCH_CATEGORY_EXPENSES_SUCCESS =
  "FETCH_CATEGORY_EXPENSES_SUCCESS";
export const FETCH_CATEGORY_EXPENSES_FAILURE =
  "FETCH_CATEGORY_EXPENSES_FAILURE";

export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAILURE = "DELETE_CATEGORY_FAILURE";
