// Action types for chat
export const SEND_GROUP_CHAT = "SEND_GROUP_CHAT";
export const SEND_GROUP_CHAT_SUCCESS = "SEND_GROUP_CHAT_SUCCESS";
export const SEND_GROUP_CHAT_FAILURE = "SEND_GROUP_CHAT_FAILURE";

export const FETCH_GROUP_CHAT = "FETCH_GROUP_CHAT";
export const FETCH_GROUP_CHAT_SUCCESS = "FETCH_GROUP_CHAT_SUCCESS";
export const FETCH_GROUP_CHAT_FAILURE = "FETCH_GROUP_CHAT_FAILURE";

export const FETCH_GROUP_CHAT_HISTORY = "FETCH_GROUP_CHAT_HISTORY";
export const FETCH_GROUP_CHAT_HISTORY_SUCCESS =
  "FETCH_GROUP_CHAT_HISTORY_SUCCESS";
export const FETCH_GROUP_CHAT_HISTORY_FAILURE =
  "FETCH_GROUP_CHAT_HISTORY_FAILURE";

export const DELETE_CHAT_MESSAGE = "DELETE_CHAT_MESSAGE";
export const DELETE_CHAT_MESSAGE_SUCCESS = "DELETE_CHAT_MESSAGE_SUCCESS";
export const DELETE_CHAT_MESSAGE_FAILURE = "DELETE_CHAT_MESSAGE_FAILURE";

export const EDIT_CHAT_MESSAGE = "EDIT_CHAT_MESSAGE";
export const EDIT_CHAT_MESSAGE_SUCCESS = "EDIT_CHAT_MESSAGE_SUCCESS";
export const EDIT_CHAT_MESSAGE_FAILURE = "EDIT_CHAT_MESSAGE_FAILURE";

export const BULK_DELETE_CHAT_MESSAGES = "BULK_DELETE_CHAT_MESSAGES";
export const BULK_DELETE_CHAT_MESSAGES_SUCCESS =
  "BULK_DELETE_CHAT_MESSAGES_SUCCESS";
export const BULK_DELETE_CHAT_MESSAGES_FAILURE =
  "BULK_DELETE_CHAT_MESSAGES_FAILURE";

export const FETCH_UNREAD_GROUP_CHAT = "FETCH_UNREAD_GROUP_CHAT";
export const FETCH_UNREAD_GROUP_CHAT_SUCCESS =
  "FETCH_UNREAD_GROUP_CHAT_SUCCESS";
export const FETCH_UNREAD_GROUP_CHAT_FAILURE =
  "FETCH_UNREAD_GROUP_CHAT_FAILURE";

// Reply to a chat message
export const REPLY_CHAT = "REPLY_CHAT";
export const REPLY_CHAT_SUCCESS = "REPLY_CHAT_SUCCESS";
export const REPLY_CHAT_FAILURE = "REPLY_CHAT_FAILURE";
