export const INVITE_FRIEND_TO_GROUP_REQUEST = "INVITE_FRIEND_TO_GROUP_REQUEST";
export const INVITE_FRIEND_TO_GROUP_SUCCESS = "INVITE_FRIEND_TO_GROUP_SUCCESS";
export const INVITE_FRIEND_TO_GROUP_FAILURE = "INVITE_FRIEND_TO_GROUP_FAILURE";
export const FETCH_FRIENDS_NOT_IN_GROUP_REQUEST =
  "FETCH_FRIENDS_NOT_IN_GROUP_REQUEST";
export const FETCH_FRIENDS_NOT_IN_GROUP_SUCCESS =
  "FETCH_FRIENDS_NOT_IN_GROUP_SUCCESS";
export const FETCH_FRIENDS_NOT_IN_GROUP_FAILURE =
  "FETCH_FRIENDS_NOT_IN_GROUP_FAILURE";
export const CREATE_GROUP_REQUEST = "CREATE_GROUP_REQUEST";
export const CREATE_GROUP_SUCCESS = "CREATE_GROUP_SUCCESS";
export const CREATE_GROUP_FAILURE = "CREATE_GROUP_FAILURE";

export const FETCH_PENDING_INVITATIONS_REQUEST =
  "FETCH_PENDING_INVITATIONS_REQUEST";
export const FETCH_PENDING_INVITATIONS_SUCCESS =
  "FETCH_PENDING_INVITATIONS_SUCCESS";
export const FETCH_PENDING_INVITATIONS_FAILURE =
  "FETCH_PENDING_INVITATIONS_FAILURE";

export const FETCH_GROUP_RECOMMENDATIONS_REQUEST =
  "FETCH_GROUP_RECOMMENDATIONS_REQUEST";
export const FETCH_GROUP_RECOMMENDATIONS_SUCCESS =
  "FETCH_GROUP_RECOMMENDATIONS_SUCCESS";
export const FETCH_GROUP_RECOMMENDATIONS_FAILURE =
  "FETCH_GROUP_RECOMMENDATIONS_FAILURE";

export const FETCH_USER_GROUPS_REQUEST = "FETCH_USER_GROUPS_REQUEST";
export const FETCH_USER_GROUPS_SUCCESS = "FETCH_USER_GROUPS_SUCCESS";
export const FETCH_USER_GROUPS_FAILURE = "FETCH_USER_GROUPS_FAILURE";

export const FETCH_ALL_GROUPS_REQUEST = "FETCH_ALL_GROUPS_REQUEST";
export const FETCH_ALL_GROUPS_SUCCESS = "FETCH_ALL_GROUPS_SUCCESS";
export const FETCH_ALL_GROUPS_FAILURE = "FETCH_ALL_GROUPS_FAILURE";

export const RESPOND_INVITATION_REQUEST = "RESPOND_INVITATION_REQUEST";
export const RESPOND_INVITATION_SUCCESS = "RESPOND_INVITATION_SUCCESS";
export const RESPOND_INVITATION_FAILURE = "RESPOND_INVITATION_FAILURE";

export const LEAVE_GROUP_REQUEST = "LEAVE_GROUP_REQUEST";
export const LEAVE_GROUP_SUCCESS = "LEAVE_GROUP_SUCCESS";
export const LEAVE_GROUP_FAILURE = "LEAVE_GROUP_FAILURE";

export const GET_GROUP_BY_ID_REQUEST = "GET_GROUP_BY_ID_REQUEST";
export const GET_GROUP_BY_ID_SUCCESS = "GET_GROUP_BY_ID_SUCCESS";
export const GET_GROUP_BY_ID_FAILURE = "GET_GROUP_BY_ID_FAILURE";

export const FETCH_SENT_INVITATIONS_REQUEST = "FETCH_SENT_INVITATIONS_REQUEST";
export const FETCH_SENT_INVITATIONS_SUCCESS = "FETCH_SENT_INVITATIONS_SUCCESS";
export const FETCH_SENT_INVITATIONS_FAILURE = "FETCH_SENT_INVITATIONS_FAILURE";

export const CANCEL_INVITATION_REQUEST = "CANCEL_INVITATION_REQUEST";
export const CANCEL_INVITATION_SUCCESS = "CANCEL_INVITATION_SUCCESS";
export const CANCEL_INVITATION_FAILURE = "CANCEL_INVITATION_FAILURE";
